config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]
  resources :articles
  resources :relationships
  get '/notifications' => 'articles#notifications'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

  def self.user_articles(userid)
    Article.find_by_sql <<-SQL
      SELECT * FROM articles WHERE user_id = #{userid}
    SQL
  end

  def self.sorted_latest_articles(following)
    Article.find_by_sql <<-SQL
                  select * from (select * from (select articles.*, dense_rank() over(partition by articles.user_id 
                  order by articles.updated_at desc) as t_rank from articles where articles.user_id 
                  in (#{following.nil? || following.empty? ? 'NULL': following.join(',')})) as latest_articles 
                  order by latest_articles.updated_at desc) as sorted_latest_articles where t_rank <= 1
    SQL
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :articles, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  before_save { self.email = email.downcase }

  validates :username, presence: true,

            uniqueness: { case_sensitive: false },

            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 105 },

            uniqueness: { case_sensitive: false },

            format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  # helper methods

  # follow another user
  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  # unfollow a user
  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  # is following a user?
  def following?(other)
    following.include?(other)
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def home

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.

# For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user

    @current_user ||= User.find(session[:user_id]) if session[:user_id]

  end

  def logged_in?

    !!current_user

  end

  def require_user

    if !logged_in?

      flash[:danger] = "You must be logged in to perform that action"

      redirect_to root_path

    end

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]


  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
  end

  def notifications
    @articles = Article.sorted_latest_articles(current_user.following.ids)
    @articles = @articles.paginate(page: params[:page], per_page: 5)
  end

  def new

    @article = Article.new

  end

  def create
    @article = Article.new(article_params)

    @article.user = current_user

    if @article.save

      flash[:success] = "Tweet was successfully created"

      redirect_to article_path(@article)

    else

      render 'new'

    end

  end

  def show

  end

  def destroy

    @article.destroy

    flash[:danger] = "Tweet was successfully deleted"

    redirect_to articles_path

  end

  private

  def set_article

    @article = Article.find(params[:id])

  end

  def article_params

    params.require(:article).permit(:title, :description)

  end

  def require_same_user

    if current_user != @article.user && !current_user.admin?

      flash[:danger] = "You can only edit or delete your own articles"

      redirect_to root_path

    end

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

    redirect_to articles_path if logged_in?

  end
  def about

  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    
    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_back fallback_location: users_path
    end

    def destroy
        user = Relationship.find(params[:id]).followed
        current_user.unfollow(user)
        redirect_back fallback_location: users_path
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])

      session[:user_id] = user.id

      flash[:success] = "You have successfully logged in"

      redirect_to user_path(user)

    else

      flash.now[:danger] = "There was something wrong with your login information"

      render 'new'

    end

  end

  def destroy

    session[:user_id] = nil

    flash[:success] = "You have logged out"

    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]

  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)

  end

  def new

    @user = User.new

  end

  def create

    @user = User.new(user_params)

    if @user.save

      session[:user_id] = @user.id

      flash[:success] = "Welcome to the revenge twitter app #{@user.username}"

      redirect_to user_path(@user)

    else

      render 'new'

    end

  end

  def edit

  end

  def update

    if @user.update(user_params)

      flash[:success] = "Your account was updated successfully"

      redirect_to articles_path

    else

      render 'edit'

    end

  end

  def show
    @user_articles = Article.user_articles(params[:id])
    @user_articles = @user_articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy

    @user = User.find(params[:id])

    @user.destroy

    flash[:danger] = "User and all articles created by user have been deleted"

    redirect_to users_path

  end

  private

  def user_params

    params.require(:user).permit(:username, :email, :password)

  end

  def set_user

    @user = User.find(params[:id])

  end

  def require_same_user

    if current_user != @user and !current_user.admin?

      flash[:danger] = "You can only edit your own account"

      redirect_to root_path

    end

  end

  def require_admin

    if logged_in? and !current_user.admin?

      flash[:danger] = "Only admin users can perform that action"

      redirect_to root_path

    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})

    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)

    size = options[:size]

    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    image_tag(gravatar_url, alt: user.username, class: "img-circle")

  end
end

app/views/articles/_article.html.haml
- obj.each do |article|
  .row
    .col-xs-8.col-xs-offset-2
      .well.well-lg
        .article-title
          = link_to article.title, article_path(article)
        .article-body
          = truncate(article.description, length: 100)
          .article-meta-details
            %small
              Created by: #{article.user.username if article.user},
              
              \#{time_ago_in_words(article.created_at)} ago; #{article.created_at.to_formatted_s(:short)}
        - if logged_in? && (current_user == article.user || current_user.admin?)
          .article-actions
            = link_to "Delete this tweet", article_path(article), method: :delete, |
              data: { confirm: "Are you sure you want to delete the article?"},    |
              class: "btn btn-xs btn-danger"                                       |

app/views/articles/_form.html.haml
= render 'shared/errors', obj: @article
.row
  .col-xs-12
    = form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f|
      .form-group
        .control-label.col-sm-2
          = f.label :title
        .col-sm-8
          = f.text_field :title, class: "form-control", placeholder: "Tweet Title", autofocus: true
      .form-group
        .control-label.col-sm-2
          = f.label :description
        .col-sm-8
          = f.text_area :description, class: "form-control", placeholder: "Tweet Body", rows: 10
      .form-group
        .col-sm-10.col-sm-offset-2
          = f.submit "Post tweet", class: 'btn btn-primary btn-lg'
    .col-xs-4.col-xs-offset-4
      [ #{link_to "Cancel request and go back", articles_path} ]

app/views/articles/index.html.haml
%h1{:align => "center"} All tweets
%div{:align => "center"}
  = will_paginate
= render 'article', obj: @articles
%div{:align => "center"}
  = will_paginate

app/views/articles/new.html.haml
%h1{:align => "center"} New Tweet
= render 'form'

app/views/articles/notifications.html.haml
%h1{:align => "center"} Notifications
%div{:align => "center"}
  = will_paginate
= render 'article', obj: @articles
%div{:align => "center"}
  = will_paginate

app/views/articles/show.html.haml
%h2{:align => "center"}
  Title: #{@article.title}
.well.col-xs-8.col-xs-offset-2
  - if @article.user
    %ul.listing
      .row.center
        .col-md-4.col-md-offset-4
          %li Created by:
          %li= link_to gravatar_for(@article.user), user_path(@article.user)
          %li.article-title
            = link_to @article.user.username, user_path(@article.user)
          %li
            %small
              = pluralize(@article.user.articles.count, "tweet") if @article.user.articles
  %h4.center.description
    %strong Description:
  %hr/
  = simple_format(@article.description)
  .article-actions
    - if logged_in? && (current_user == @article.user || current_user.admin?)
      = link_to "Delete this tweet", article_path(@article), method: :delete, |
        data: { confirm: "Are you sure you want to delete the article?"},     |
        class: "btn btn-xs btn-danger"                                        |
    = link_to "View all tweets", articles_path, class: "btn btn-xs btn-success"

app/views/layouts/_footer.html.haml
.container
  %footer.footer
    %small
      Copyright ©
      %a{:href => "https://www.castlighthealth.com/", :target => "_blank"} Castlight Health
      by
      %a{:href => "https://github.com/syahmeds", :target => "_blank"} Ahmed Syed
    %nav
      %ul
        %li= link_to "About", about_path

app/views/layouts/_messages.html.haml
.row
  .col-xs-10.col-xs-offset-1
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "RevTwitter", root_path, class: "navbar-brand", id: "logo"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if logged_in?
          %li
            %a{:href => "/notifications"} Notifications
          %li= link_to "Users", users_path
          %li= link_to "Post", new_article_path
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li= link_to 'Log out', logout_path, method: :delete
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              #{current_user.username.capitalize}
              %span.caret
            %ul.dropdown-menu
              %li= link_to "Edit your profile", edit_user_path(current_user)
              %li= link_to "View your profile", user_path(current_user)
        - else
          %li= link_to 'Log in', login_path
          %li= link_to 'Sign up', signup_path
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AlphaBlog
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    .container
      = yield
    = render 'layouts/footer'

app/views/pages/about.html.haml
%h1 Welcome to the about page
= link_to 'Home', root_path

app/views/pages/home.html.haml
.center.jumbotron
  %h1 Welcome to the Revenge Social Network
  %p{:style => "text-align:center;"}
    = link_to "Sign up", signup_path, class: "btn btn-primary"
    = link_to "Login", login_path, class: "btn btn-primary"

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .row
    .col-xs-8.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(obj.errors.count, "error")
            prohibited this article from being saved:
          .panel-body
            %ul
              - obj.errors.full_messages.each do |msg|
                %li= msg

app/views/users/_form.html.haml
= render 'shared/errors', obj: @user
.row
  .col-xs-12
    = form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f|
      .form-group
        .control-label.col-sm-2
          = f.label :username
        .col-sm-8
          = f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true
      .form-group
        .control-label.col-sm-2
          = f.label :email
        .col-sm-8
          = f.email_field :email, class: "form-control", placeholder: "Enter email"
      .form-group
        .control-label.col-sm-2
          = f.label :password
        .col-sm-8
          = f.password_field :password, class: "form-control", placeholder: "Enter password"
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg')
    .col-xs-4.col-xs-offset-4
      [ #{link_to "Cancel request and go back", articles_path} ]

app/views/users/edit.html.haml
%h1{:align => "center"} Edit your account
= render 'form'

app/views/users/index.html.haml
%h1{:align => "center"} All Users
%div{:align => "center"}
  = will_paginate
  - @users.each do |user|
    %ul.listing
      .row
        .well.col-md-4.col-md-offset-4
          %li= link_to gravatar_for(user), user_path(user)
          %li.article-title
            = link_to user.username, user_path(user)
          - if logged_in? && !(current_user.id == user.id)
            - if !current_user.following?(user)
              = form_for(current_user.active_relationships.build) do |f|
                %div= hidden_field_tag :followed_id, user.id
                = f.submit "Follow", class: "btn btn-primary"
            - else
              = form_for(current_user.active_relationships.find_by(followed_id: user.id), |
                html: { method: :delete }) do |f|                                                         |
                = f.submit "Unfollow", class: "btn btn-primary"
          %li
            %small= pluralize(user.articles.count, "tweet") if user.articles
          - if logged_in? and current_user.admin?
            %li= link_to "Delete this user", user_path(user), method: :delete,                         |
                data: { confirm: "Are you sure you want to delete the user and all their articles?" } |
  = will_paginate

app/views/users/new.html.haml
%h1{:align => "center"} Sign up
= render 'form'

app/views/users/show.html.haml
%h1{:align => "center"}
  Welcome to #{@user.username}'s page
.row
  .col-md-4.col-md-offset-4.center
    = gravatar_for @user, size: 150
%h4{:align => "center"}
  = @user.username
  's tweets
.center
  = will_paginate @user_articles
= render 'articles/article', obj: @user_articles
.center
  = will_paginate @user_articles